version: '3.1'
services:
    php-apache-environment:
        container_name: apachephp
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: lVkYWB5gCxM52
            MYSQL_DATABASE: phptest
            MYSQL_USER: phptest
            MYSQL_PASSWORD: lVkYWB5gCxM52
        volumes:
            - ./mysql-data/:/var/lib/mysql
        ports:
            - "3306:3306"